### ISSUE TITLE
Cloudflare - if not entitled to block, allow for using Challenge or JS Challenge (available in all plans)

### ISSUE THREAD

**Issue by mjpcomp** [dvershinin/fds#11]
Feature Request:

Since the country block is only available for certain plans, and not everyone may be subscribed to those, it would be nice to add the ability to set the configuration for fds to use the challenge option or js-challenge option for the country, or, add it as a CLI option (e.g. _fds block Country1 challenge_)

![image](https://user-images.githubusercontent.com/7637082/113821990-b45b3500-9731-11eb-9774-48074dfa6214.png)

Maybe a future option will give the ability to add/update firewall rules with the country block, but, that's probably going to take a little more coding to make happen...

**Comment by dvershinin** [comment]
Added in v0.0.18. Will fall back to Captcha challenge, as I believe it's more restricting than Js based challenge.
Example:

```
#> fds block China

Blocking China 🇨🇳
Downloaded /var/lib/fds/cn.zone: : 80.0KB [00:00, 186206.61KB/s]                                                                                      
Reloading FirewallD...
Done!
Setting access rule to block China in Cloudflare account Test@Test
Not entitled to block countries in Cloudflare. Setting Captcha challenge instead
Setting access rule to challenge China in Cloudflare account Test@Test
```
