### ISSUE TITLE
Changing Cloudflare API token

### ISSUE THREAD

**Issue by KubLuk24** [dvershinin/fds#19]
Hey,
is there a way to change the Cloudflare API token? I accidentally entered a wrong one and can't find a way to change it anywhere.
I tried running the config command again and uninstalling FDS including all files but nothing helped.

**Comment by dvershinin** [comment]
You can manually edit `/root/.cloudflare/cloudflare.cfg` with the correct token value; or delete it, then run `fds config` again.

**Comment by KubLuk24** [comment]
Thanks, worked!
