### ISSUE TITLE
Blocking tor exit nodes fails

### ISSUE THREAD

**Issue by ux24** [dvershinin/fds#38]
Tor exit node list in lists.fissionrelays.net is not available anymore, therefore tor exit node blocking does not work:

requests.exceptions.ConnectionError: HTTPSConnectionPool(host='lists.fissionrelays.net', port=443): Max retries exceeded with url: /tor/exits-ipv4.txt (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb36700bd30>: Failed to establish a new connection: [Errno -2] Name or service not known',))

Maybe https://openinternet.io/tor/tor-exit-list.txt could be used instead?

**Comment by dvershinin** [comment]
@ux24 thank you for the link. Fixed in the latest release.
