### ISSUE TITLE
Is there a way to list existing block entries?

### ISSUE THREAD

**Issue by fivz** [dvershinin/fds#4]
Is there a way to list existing block entries?
Is there a way to choose some of them for removal?

**Comment by dvershinin** [comment]
For unblocking, you can:

    fds unblock 1.2.3.4
    fds unblock China

(will update documentation)

Listing is not yet supported, but you can resort to `ipset` utility, e.g. since IPv4 block entries are put to `networkblock4` IP set:

    ipset -L networkblock4

**Comment by dvershinin** [comment]
Added `fds list blocked` in the latest version.
