### ISSUE TITLE
Sorry not an issue - request to add IP set

### ISSUE THREAD

**Issue by HawaiiWes** [dvershinin/fds#5]
This will save me tons of time - thanks for that.
One request - I find many hackers come in via TOR - would be nice if you could include a set for this IP list also.
Thanks, Wes

**Comment by dvershinin** [comment]
Good suggestion. Will be added when I have the time (some example [reference implementation](http://webcache.googleusercontent.com/search?q=cache:INVTbjxo43IJ:https://eitsonline.com/2017/05/29/programmatically-block-tor-networks-easily/&client=safari&hl=en&gl=ru&strip=1&vwsrc=0))

**Comment by dvershinin** [comment]
A more convenient source of exit node lists (ipv4 and ipv6) found [here](https://fissionrelays.net/lists)

**Comment by dvershinin** [comment]
Added in v0.0.9. Can run:

    fds block tor

Feel free to reopen if there's an issue about it.
